[package]
name = "curses_snake"
version = "0.1.0"
authors = ["Rasmus <rasmus.kallqvist@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.8", features = ["std", "consoleapi", "processenv", "winbase", "wincon", "impl-default", "profileapi", "winuser"] }
pdcurses-sys = { git = "https://github.com/warwolt/pdcurses-sys-wmcbrine", branch="main" }
pancurses = { git = "https://github.com/warwolt/pancurses" }
keyboard_input = { path = "./keyboard_input" }
