[package]
name = "curses_snake"
version = "0.1.0"
authors = ["Rasmus <rasmus.kallqvist@gmail.com>"]
edition = "2018"

[dependencies]
pdcurses-sys = { git = "https://github.com/warwolt/pdcurses-sys-wmcbrine", branch="main" }
pancurses = { git = "https://github.com/warwolt/pancurses" }
platform = { path = "./platform" }
