[package]
name = "curses_snake"
version = "0.1.0"
authors = ["Rasmus <rasmus.kallqvist@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.8", features = ["std", "consoleapi", "processenv", "winbase", "wincon", "impl-default", "profileapi", "winuser"] }
pancurses = { version = "0.16", features = ["win32"]}
