[package]
name = "platform"
version = "0.1.0"
authors = ["Rasmus <rasmus.kallqvist@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.8", features = ["std", "winnt", "winuser"] }
